# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        mongodb-version: ['3.6', '4.0', '4.2']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    # - run: npm i --no-audit
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # - run: npm ci
    - run: npm config set send-metrics false
    - name: Run build script
      run: ./scripts/travis/install_mongodb.sh
      shell: bash
    - name: Run build script
      run: ./scripts/travis/run_mongodb.sh
      shell: bash
    # - run: npm run build --if-present
    - run: npm test
    - run: pkill mongod
